### ISSUE TITLE
Hope to call out the command line for std input

### ISSUE THREAD

**Issue by AdaChambers** [quarnster/SublimeGDB#112]
Hi,sir. Thanks for your incredible job for a gdb debugging plugin of subime-text. Like the russian guy said a few years ago, I myself also have a problem in inputting data when using sublimeGDB.You know, I use to use DEV-C++, MinGW developer studio or Visual Studio for c/c++ programming. And when using the graphic-user-interface buttons of those IDEs to debug, it jumps out a black cmd window waiting for you to input. Only after you input, will the debugger step into the next line... But in sublime-text it just step over the current sentence(scanf or cin...)and point to the next line with a random number given to the variable I want ot read. I just don't know how to using sublimwGDB to input,without typing the gdb commands in the cmd window... Is that a possible choice?(And I am also not a native English speaker but I just think English may be the social language on an internation online platform...)

**Comment by mheinzler** [comment]
You can just enter the data into the input field (`Shift+F5`). The problem is that SublimeGDB uses the machine interface interpreter (`mi`) of GDB and prefixes every line of input with a number. This number is what you get as a result of `cin`. But I don't know why it automatically steps over because for me `GDB` is waiting for input on those lines.

But as the input thing is something I could also use, I just implemented it on top of my own changes: https://github.com/mheinzler/SublimeGDB/commit/ad3d18e4a8bddbd31770eea0f2f711913036b6d3

If you want you can try it out from here: https://github.com/mheinzler/SublimeGDB
Just uninstall your current `SublimeGDB` and clone this into your `Packages` directory. Then you can open the raw input field with `Ctrl+Shift+F5` to enter some input when your program is waiting for it.

Maybe this helps :smile:.
