### ISSUE TITLE
error when trying to run 

### ISSUE THREAD

**Issue by ReintH** [quarnster/SublimeGDB#82]
im receiving a error when im trying to run SublimeGDB on Sublime Text 2. For some reason this error shows up:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./sublimegdb.py", line 1597, in run
  File "./sublimegdb.py", line 109, in expand_path
AttributeError: 'Window' object has no attribute 'extract_variables'

i mentioned that  the extract_variables function is not present in the Sublime Text 2 api which possibly causes the error.

**Comment by michaelkschmidt** [comment]
@ReintH Sorry about that.  quarnster/SublimeGDB#80 was the source of the problem, and has been reverted.  Apparently getattr() must be used instead of looking directly at window.extract_variables 

In theory Package Control should see the fixed version in the next hour or so.  Let me know if you still have issues.

**Comment by ReintH** [comment]
This fixed the problem, Thanks!
